# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  workflow_dispatch:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Run test
      run: |
        python3 -c "print('all tests have passed')"

    - uses: mshick/add-pr-comment@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        message: |
          ![Seekret](https://seekret.io/wp-content/uploads/2021/10/finallogo-2.png)

          Mapping summary for "feature/change" (compared with "Stable"):

          * **1** endpoint changed
          * **0** endpoints removed
          * **0** endpoints changed


          You can view a full summary using the [Seekret platform](https://play.seekret.io/PR/changes?envLeft=%22PR%22&envRight=%22PR%22&revisionLeft=%22d5665380-f921-4c44-beef-4953ee4f1097%22&revisionRight=%22766fa56a-b8e1-423a-8833-11073e314171%22)
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
        allow-repeats: false # This is the default
